# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170827_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
